# Generated by Django 2.1.5 on 2019-01-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='seconds',
            field=models.IntegerField(blank=True, verbose_name='Seconds deposited'),
        ),
    ]
